/* Gói nguồn VN: đại học, thư viện, LMS, tuyển sinh/đề thi, Sở GDĐT, trường chuyên */
(function (global) {
  var PAL = ['#dbeafe','#fef3c7','#dcfce7','#e0e7ff','#fce7f3','#ffedd5','#cffafe','#ede9fe','#fee2e2','#d1fae5','#ddd6fe','#fef9c3'];
  var n = 0;
  function col() { return PAL[(n++) % PAL.length]; }
  function it(cat, icon, title, source, desc, url, tags) {
    return { cat: cat, icon: icon, color: col(), title: title, source: source, desc: desc, url: url, tags: tags };
  }

  var pack = [];

  /* name, short, region, home, lib, tuyensinh, lms */
  var unis = [
    ['Đại học Bách khoa Hà Nội','HUST','Hà Nội','https://hust.edu.vn','https://library.hust.edu.vn','https://ts.hust.edu.vn','https://lms.hust.edu.vn'],
    ['Đại học Khoa học Tự nhiên — ĐHQGHN','HUS','Hà Nội','https://hus.vnu.edu.vn','','https://hus.vnu.edu.vn/tuyensinh','https://courses.hus.vnu.edu.vn'],
    ['Đại học Công nghệ — ĐHQGHN','UET','Hà Nội','https://uet.vnu.edu.vn','https://lib.uet.vnu.edu.vn','https://uet.vnu.edu.vn/tuyensinh',''],
    ['Đại học Kinh tế — ĐHQGHN','UEB','Hà Nội','https://ueb.vnu.edu.vn','','https://ueb.edu.vn/tuyensinh',''],
    ['Đại học Ngoại ngữ — ĐHQGHN','ULIS','Hà Nội','https://ulis.vnu.edu.vn','https://library.ulis.vnu.edu.vn','https://ulis.vnu.edu.vn/tuyensinh',''],
    ['Đại học Khoa học Xã hội và Nhân văn — ĐHQGHN','USSH HN','Hà Nội','https://ussh.vnu.edu.vn','https://lib.ussh.vnu.edu.vn','https://ussh.vnu.edu.vn/tuyensinh',''],
    ['Trường Đại học Giáo dục — ĐHQGHN','UED-VNU','Hà Nội','https://education.vnu.edu.vn','','https://education.vnu.edu.vn',''],
    ['Trường Đại học Luật — ĐHQGHN','VNU-UL','Hà Nội','https://law.vnu.edu.vn','','https://law.vnu.edu.vn',''],
    ['Trường Quốc tế — ĐHQGHN','VNU-IS','Hà Nội','https://is.vnu.edu.vn','','https://is.vnu.edu.vn/admissions',''],
    ['Đại học Việt Nhật','VJU','Hà Nội','https://vju.ac.vn','','https://vju.ac.vn/tuyen-sinh',''],
    ['Đại học Quốc gia TP.HCM','ĐHQG-HCM','TP.HCM','https://vnuhcm.edu.vn','https://www.vnulib.edu.vn','https://tuyensinh.vnuhcm.edu.vn',''],
    ['Đại học Khoa học Tự nhiên — ĐHQG-HCM','HCMUS','TP.HCM','https://hcmus.edu.vn','https://glib.hcmus.edu.vn','https://hcmus.edu.vn/tuyen-sinh','https://courses.hcmus.edu.vn'],
    ['Đại học Bách khoa TP.HCM','HCMUT','TP.HCM','https://hcmut.edu.vn','https://lib.hcmut.edu.vn','https://ts.hcmut.edu.vn','https://lms.hcmut.edu.vn'],
    ['Đại học Công nghệ Thông tin — ĐHQG-HCM','UIT','TP.HCM','https://uit.edu.vn','https://lib.uit.edu.vn','https://tuyensinh.uit.edu.vn',''],
    ['Đại học Quốc tế — ĐHQG-HCM','HCMIU','TP.HCM','https://hcmiu.edu.vn','https://library.hcmiu.edu.vn','https://hcmiu.edu.vn/admissions',''],
    ['Đại học Kinh tế – Luật','UEL','TP.HCM','https://uel.edu.vn','https://lib.uel.edu.vn','https://tuyensinh.uel.edu.vn',''],
    ['Đại học KHXH&NV — ĐHQG-HCM','HCMUSSH','TP.HCM','https://hcmussh.edu.vn','https://lib.hcmussh.edu.vn','https://hcmussh.edu.vn/tuyensinh',''],
    ['Đại học Sư phạm Hà Nội','HNUE','Hà Nội','https://www.hnue.edu.vn','https://lib.hnue.edu.vn','https://tuyensinh.hnue.edu.vn',''],
    ['Đại học Sư phạm TP.HCM','HCMUE','TP.HCM','https://hcmue.edu.vn','https://lib.hcmue.edu.vn','https://tuyensinh.hcmue.edu.vn',''],
    ['Đại học Sư phạm Kỹ thuật TP.HCM','HCMUTE','TP.HCM','https://hcmute.edu.vn','https://lib.hcmute.edu.vn','https://ts.hcmute.edu.vn','https://lms.hcmute.edu.vn'],
    ['Đại học Kinh tế Quốc dân','NEU','Hà Nội','https://neu.edu.vn','https://lib.neu.edu.vn','https://tuyensinh.neu.edu.vn',''],
    ['Đại học Kinh tế TP.HCM','UEH','TP.HCM','https://ueh.edu.vn','https://lib.ueh.edu.vn','https://tuyensinh.ueh.edu.vn','https://lms.ueh.edu.vn'],
    ['Đại học Ngoại thương','FTU','Hà Nội','https://ftu.edu.vn','https://lib.ftu.edu.vn','https://tuyensinh.ftu.edu.vn',''],
    ['Đại học Y Hà Nội','HMU','Hà Nội','https://hmu.edu.vn','https://thuvien.hmu.edu.vn','https://hmu.edu.vn/tuyensinh',''],
    ['Đại học Y Dược TP.HCM','UMP','TP.HCM','https://ump.edu.vn','https://lib.ump.edu.vn','https://ump.edu.vn/tuyen-sinh',''],
    ['Đại học Xây dựng Hà Nội','HUCE','Hà Nội','https://huce.edu.vn','https://thuvien.huce.edu.vn','https://huce.edu.vn/tuyensinh',''],
    ['Đại học Giao thông vận tải','UTC','Hà Nội','https://utc.edu.vn','https://lib.utc.edu.vn','https://tuyensinh.utc.edu.vn',''],
    ['Đại học Giao thông vận tải TP.HCM','UTH','TP.HCM','https://ut.edu.vn','https://lib.ut.edu.vn','https://ut.edu.vn/tuyen-sinh',''],
    ['Đại học Mỏ – Địa chất','HUMG','Hà Nội','https://humg.edu.vn','https://lib.humg.edu.vn','https://humg.edu.vn/tuyensinh',''],
    ['Đại học Thủy lợi','TLU','Hà Nội','https://tlu.edu.vn','https://lib.tlu.edu.vn','https://tlu.edu.vn/tuyensinh',''],
    ['Học viện Nông nghiệp Việt Nam','VNUA','Hà Nội','https://vnua.edu.vn','https://library.vnua.edu.vn','https://tuyensinh.vnua.edu.vn',''],
    ['Đại học Nông Lâm TP.HCM','NLU','TP.HCM','https://hcmuaf.edu.vn','https://lib.hcmuaf.edu.vn','https://hcmuaf.edu.vn/tuyen-sinh',''],
    ['Đại học Hà Nội','HANU','Hà Nội','https://hanu.edu.vn','https://lib.hanu.edu.vn','https://tuyensinh.hanu.edu.vn',''],
    ['Đại học Công nghiệp Hà Nội','HAUI','Hà Nội','https://haui.edu.vn','https://lib.haui.edu.vn','https://tuyensinh.haui.edu.vn','https://e.haui.edu.vn'],
    ['Đại học Điện lực','EPU','Hà Nội','https://epu.edu.vn','https://thuvien.epu.edu.vn','https://epu.edu.vn/tuyensinh',''],
    ['Đại học Công nghệ Giao thông vận tải','UTT','Hà Nội','https://utt.edu.vn','https://lib.utt.edu.vn','https://utt.edu.vn/tuyensinh',''],
    ['Đại học Tài nguyên và Môi trường Hà Nội','HUNRE','Hà Nội','https://hunre.edu.vn','https://lib.hunre.edu.vn','https://hunre.edu.vn/tuyensinh',''],
    ['Đại học Thương mại','TMU','Hà Nội','https://tmu.edu.vn','https://lib.tmu.edu.vn','https://tmu.edu.vn/tuyensinh',''],
    ['Học viện Tài chính','AOF','Hà Nội','https://hvtc.edu.vn','https://thuvien.hvtc.edu.vn','https://hvtc.edu.vn/tuyensinh',''],
    ['Học viện Ngân hàng','HVNH','Hà Nội','https://hvnh.edu.vn','https://lib.hvnh.edu.vn','https://hvnh.edu.vn/tuyensinh',''],
    ['Đại học Luật Hà Nội','HLU','Hà Nội','https://hlu.edu.vn','https://thuvien.hlu.edu.vn','https://hlu.edu.vn/tuyensinh',''],
    ['Đại học Luật TP.HCM','HCMULAW','TP.HCM','https://hcmulaw.edu.vn','https://lib.hcmulaw.edu.vn','https://hcmulaw.edu.vn/tuyen-sinh',''],
    ['Đại học Kiến trúc Hà Nội','HAU','Hà Nội','https://hau.edu.vn','https://lib.hau.edu.vn','https://hau.edu.vn/tuyensinh',''],
    ['Đại học Kiến trúc TP.HCM','UAH','TP.HCM','https://uah.edu.vn','https://lib.uah.edu.vn','https://uah.edu.vn/tuyen-sinh',''],
    ['Đại học Sài Gòn','SGU','TP.HCM','https://sgu.edu.vn','https://lib.sgu.edu.vn','https://sgu.edu.vn/tuyen-sinh',''],
    ['Đại học Công nghiệp TP.HCM','IUH','TP.HCM','https://iuh.edu.vn','https://lib.iuh.edu.vn','https://tuyensinh.iuh.edu.vn',''],
    ['Đại học Công Thương TP.HCM','HUFI','TP.HCM','https://hufi.edu.vn','https://lib.hufi.edu.vn','https://hufi.edu.vn/tuyen-sinh',''],
    ['Đại học Mở Hà Nội','HOU','Hà Nội','https://hou.edu.vn','https://lib.hou.edu.vn','https://hou.edu.vn/tuyensinh','https://lms.hou.edu.vn'],
    ['Đại học Mở TP.HCM','OU','TP.HCM','https://ou.edu.vn','https://lib.ou.edu.vn','https://ou.edu.vn/tuyen-sinh','https://lms.ou.edu.vn'],
    ['Đại học Sư phạm Kỹ thuật Hưng Yên','UTEHY','Hưng Yên','https://utehy.edu.vn','https://lib.utehy.edu.vn','https://utehy.edu.vn/tuyensinh',''],
    ['Đại học Sư phạm Hà Nội 2','HPU2','Vĩnh Phúc','https://hpu2.edu.vn','https://lib.hpu2.edu.vn','https://hpu2.edu.vn/tuyensinh',''],
    ['Đại học Vinh','VinhUni','Nghệ An','https://vinhuni.edu.vn','https://lib.vinhuni.edu.vn','https://vinhuni.edu.vn/tuyensinh',''],
    ['Đại học Huế','HueUni','Huế','https://hueuni.edu.vn','https://lib.hueuni.edu.vn','https://hueuni.edu.vn/tuyensinh',''],
    ['Đại học Khoa học — ĐH Huế','HUSC','Huế','https://husc.edu.vn','https://lib.husc.edu.vn','https://husc.edu.vn/tuyensinh',''],
    ['Đại học Sư phạm Huế','ĐHSP Huế','Huế','https://dhsphue.edu.vn','https://thuvien.dhsphue.edu.vn','https://dhsphue.edu.vn/tuyensinh',''],
    ['Đại học Y Dược Huế','HueUMP','Huế','https://huemed-univ.edu.vn','https://lib.huemed-univ.edu.vn','https://huemed-univ.edu.vn/tuyensinh',''],
    ['Đại học Đà Nẵng','UDN','Đà Nẵng','https://www.udn.vn','','https://udn.vn/tuyensinh',''],
    ['Đại học Bách khoa Đà Nẵng','DUT','Đà Nẵng','https://dut.udn.vn','https://lib.dut.udn.vn','https://dut.udn.vn/tuyensinh',''],
    ['Đại học Sư phạm Đà Nẵng','UED','Đà Nẵng','https://ued.udn.vn','https://lib.ued.udn.vn','https://ued.udn.vn/tuyensinh',''],
    ['Đại học Sư phạm Kỹ thuật Đà Nẵng','UTE DN','Đà Nẵng','https://ute.udn.vn','https://lib.ute.udn.vn','https://ute.udn.vn/tuyensinh',''],
    ['Đại học Kinh tế Đà Nẵng','DUE','Đà Nẵng','https://due.udn.vn','https://lib.due.udn.vn','https://due.udn.vn/tuyensinh',''],
    ['Đại học Ngoại ngữ Đà Nẵng','UD-FL','Đà Nẵng','https://ufl.udn.vn','','https://ufl.udn.vn',''],
    ['Đại học Thái Nguyên','TNU','Thái Nguyên','https://tnu.edu.vn','https://lib.tnu.edu.vn','https://tnu.edu.vn/tuyensinh',''],
    ['Đại học Sư phạm Thái Nguyên','TNUE','Thái Nguyên','https://tnue.edu.vn','https://lib.tnue.edu.vn','https://tnue.edu.vn/tuyensinh',''],
    ['Đại học Kỹ thuật Công nghiệp Thái Nguyên','TNUT','Thái Nguyên','https://tnut.edu.vn','https://lib.tnut.edu.vn','https://tnut.edu.vn/tuyensinh',''],
    ['Đại học Công nghệ Thông tin & Truyền thông TN','ICTU','Thái Nguyên','https://ictu.edu.vn','https://lib.ictu.edu.vn','https://ictu.edu.vn/tuyensinh',''],
    ['Đại học Y Dược Thái Nguyên','TUMP','Thái Nguyên','https://tump.edu.vn','https://lib.tump.edu.vn','https://tump.edu.vn/tuyensinh',''],
    ['Đại học Cần Thơ','CTU','Cần Thơ','https://www.ctu.edu.vn','https://lrc.ctu.edu.vn','https://tuyensinh.ctu.edu.vn','https://elearning.ctu.edu.vn'],
    ['Đại học Y Dược Cần Thơ','CTUMP','Cần Thơ','https://ctump.edu.vn','https://lib.ctump.edu.vn','https://ctump.edu.vn/tuyen-sinh',''],
    ['Đại học Quy Nhơn','QNU','Bình Định','https://qnu.edu.vn','https://lib.qnu.edu.vn','https://qnu.edu.vn/tuyensinh',''],
    ['Đại học Nha Trang','NTU','Khánh Hòa','https://ntu.edu.vn','https://lib.ntu.edu.vn','https://ntu.edu.vn/tuyensinh',''],
    ['Đại học Đà Lạt','DLU','Lâm Đồng','https://dlu.edu.vn','https://lib.dlu.edu.vn','https://dlu.edu.vn/tuyensinh',''],
    ['Đại học Tây Nguyên','TTN','Đắk Lắk','https://ttn.edu.vn','https://lib.ttn.edu.vn','https://ttn.edu.vn/tuyensinh',''],
    ['Đại học Hồng Đức','HDU','Thanh Hóa','https://hdu.edu.vn','https://lib.hdu.edu.vn','https://hdu.edu.vn/tuyensinh',''],
    ['Đại học Hà Tĩnh','HTU','Hà Tĩnh','https://htu.edu.vn','https://lib.htu.edu.vn','https://htu.edu.vn/tuyensinh',''],
    ['Đại học Quảng Bình','QUB','Quảng Bình','https://qub.edu.vn','https://lib.qub.edu.vn','https://qub.edu.vn/tuyensinh',''],
    ['Đại học Quảng Nam','QNAM','Quảng Nam','https://qnamuni.edu.vn','','https://qnamuni.edu.vn',''],
    ['Đại học Phạm Văn Đồng','PDU','Quảng Ngãi','https://pdu.edu.vn','https://lib.pdu.edu.vn','https://pdu.edu.vn/tuyensinh',''],
    ['Đại học Phú Yên','PYU','Phú Yên','https://pyu.edu.vn','https://lib.pyu.edu.vn','https://pyu.edu.vn/tuyensinh',''],
    ['Đại học Khánh Hòa','UKH','Khánh Hòa','https://ukh.edu.vn','https://lib.ukh.edu.vn','https://ukh.edu.vn/tuyensinh',''],
    ['Đại học Hùng Vương','HVU','Phú Thọ','https://hvu.edu.vn','https://lib.hvu.edu.vn','https://hvu.edu.vn/tuyensinh',''],
    ['Đại học Tây Bắc','UTB','Sơn La','https://utb.edu.vn','https://lib.utb.edu.vn','https://utb.edu.vn/tuyensinh',''],
    ['Đại học Hải Phòng','HPU','Hải Phòng','https://dhhp.edu.vn','https://lib.dhhp.edu.vn','https://dhhp.edu.vn/tuyensinh',''],
    ['Đại học Y Dược Hải Phòng','HPMU','Hải Phòng','https://hpmu.edu.vn','https://lib.hpmu.edu.vn','https://hpmu.edu.vn/tuyensinh',''],
    ['Đại học Hàng hải Việt Nam','VMU','Hải Phòng','https://vimaru.edu.vn','https://lib.vimaru.edu.vn','https://vimaru.edu.vn/tuyensinh',''],
    ['Đại học Sư phạm Kỹ thuật Nam Định','NUTE','Nam Định','https://nute.edu.vn','https://lib.nute.edu.vn','https://nute.edu.vn/tuyensinh',''],
    ['Đại học Điều dưỡng Nam Định','NDUN','Nam Định','https://ndun.edu.vn','','https://ndun.edu.vn',''],
    ['Đại học Thái Bình','TBU','Thái Bình','https://tbu.edu.vn','https://lib.tbu.edu.vn','https://tbu.edu.vn/tuyensinh',''],
    ['Đại học Y Dược Thái Bình','TBUMP','Thái Bình','https://tbump.edu.vn','','https://tbump.edu.vn',''],
    ['Đại học Hoa Lư','HLUV','Ninh Bình','https://hluv.edu.vn','','https://hluv.edu.vn',''],
    ['Đại học Đồng Tháp','DThU','Đồng Tháp','https://dthu.edu.vn','https://lib.dthu.edu.vn','https://dthu.edu.vn/tuyensinh',''],
    ['Đại học An Giang','AGU','An Giang','https://agu.edu.vn','https://lib.agu.edu.vn','https://agu.edu.vn/tuyen-sinh',''],
    ['Đại học Trà Vinh','TVU','Trà Vinh','https://tvu.edu.vn','https://lib.tvu.edu.vn','https://tvu.edu.vn/tuyen-sinh',''],
    ['Đại học Thủ Dầu Một','TDMU','Bình Dương','https://tdmu.edu.vn','https://lib.tdmu.edu.vn','https://tdmu.edu.vn/tuyen-sinh',''],
    ['Đại học Đồng Nai','DNU','Đồng Nai','https://dnpu.edu.vn','https://lib.dnpu.edu.vn','https://dnpu.edu.vn/tuyensinh',''],
    ['Đại học Bà Rịa – Vũng Tàu','BVU','BR-VT','https://bvu.edu.vn','https://lib.bvu.edu.vn','https://bvu.edu.vn/tuyen-sinh',''],
    ['Đại học Tiền Giang','TGU','Tiền Giang','https://tgu.edu.vn','https://lib.tgu.edu.vn','https://tgu.edu.vn/tuyen-sinh',''],
    ['Đại học Kiên Giang','KGU','Kiên Giang','https://vnkgu.edu.vn','https://lib.vnkgu.edu.vn','https://vnkgu.edu.vn/tuyen-sinh',''],
    ['Đại học Bạc Liêu','BLU','Bạc Liêu','https://blu.edu.vn','https://lib.blu.edu.vn','https://blu.edu.vn/tuyen-sinh',''],
    ['Đại học Cửu Long','MKU','Vĩnh Long','https://mku.edu.vn','','https://mku.edu.vn',''],
    ['Đại học Xây dựng Miền Tây','MTU','Vĩnh Long','https://mtu.edu.vn','','https://mtu.edu.vn',''],
    ['Đại học Sư phạm Kỹ thuật Vĩnh Long','VLUTE','Vĩnh Long','https://vlute.edu.vn','https://lib.vlute.edu.vn','https://vlute.edu.vn/tuyensinh',''],
    ['Đại học Tôn Đức Thắng','TDTU','TP.HCM','https://tdtu.edu.vn','https://library.tdtu.edu.vn','https://admission.tdtu.edu.vn','https://elearning.tdtu.edu.vn'],
    ['Đại học Nguyễn Tất Thành','NTTU','TP.HCM','https://ntt.edu.vn','https://lib.ntt.edu.vn','https://ntt.edu.vn/tuyen-sinh',''],
    ['Đại học Văn Lang','VLU','TP.HCM','https://www.vlu.edu.vn','https://lib.vlu.edu.vn','https://www.vlu.edu.vn/tuyen-sinh',''],
    ['Đại học HUTECH','HUTECH','TP.HCM','https://hutech.edu.vn','https://lib.hutech.edu.vn','https://hutech.edu.vn/tuyen-sinh',''],
    ['Đại học Lạc Hồng','LHU','Đồng Nai','https://lhu.edu.vn','https://lib.lhu.edu.vn','https://lhu.edu.vn/tuyen-sinh',''],
    ['Đại học Công nghệ TP.HCM (HUTECH)','HUTECH-CN','TP.HCM','https://www.hutech.edu.vn','','',''],
    ['Đại học Hoa Sen','HSU','TP.HCM','https://www.hoasen.edu.vn','https://lib.hoasen.edu.vn','https://www.hoasen.edu.vn/tuyen-sinh',''],
    ['Đại học Hồng Bàng','HIU','TP.HCM','https://hiu.vn','https://lib.hiu.vn','https://hiu.vn/tuyen-sinh',''],
    ['Đại học FPT','FPTU','Hà Nội','https://fpt.edu.vn','https://lib.fpt.edu.vn','https://daihoc.fpt.edu.vn',''],
    ['Đại học Phenikaa','Phenikaa','Hà Nội','https://phenikaa-uni.edu.vn','https://library.phenikaa-uni.edu.vn','https://phenikaa-uni.edu.vn/tuyensinh',''],
    ['Đại học RMIT Việt Nam','RMIT','TP.HCM','https://www.rmit.edu.vn','https://www.rmit.edu.vn/library','https://www.rmit.edu.vn/study-at-rmit',''],
    ['Đại học British University Vietnam','BUV','Hà Nội','https://www.buv.edu.vn','','https://www.buv.edu.vn/admissions',''],
    ['Đại học VinUni','VinUni','Hà Nội','https://vinuni.edu.vn','https://library.vinuni.edu.vn','https://vinuni.edu.vn/admissions',''],
    ['Học viện Kỹ thuật Quân sự','LQDTU','Hà Nội','https://lqdtu.edu.vn','https://lib.lqdtu.edu.vn','https://lqdtu.edu.vn/tuyensinh',''],
    ['Học viện Quốc phòng','AND','Hà Nội','https://hocvienquocphong.edu.vn','','',''],
    ['Học viện Báo chí và Tuyên truyền','AJC','Hà Nội','https://ajc.edu.vn','https://thuvien.ajc.edu.vn','https://ajc.edu.vn/tuyensinh',''],
    ['Học viện Ngoại giao','DAV','Hà Nội','https://dav.edu.vn','https://lib.dav.edu.vn','https://dav.edu.vn/tuyensinh',''],
    ['Học viện Chính sách và Phát triển','APD','Hà Nội','https://apd.edu.vn','','https://apd.edu.vn',''],
    ['Học viện Công nghệ Bưu chính Viễn thông','PTIT','Hà Nội','https://ptit.edu.vn','https://lib.ptit.edu.vn','https://ptit.edu.vn/tuyensinh','https://lms.ptit.edu.vn'],
    ['Đại học Lâm nghiệp','VNUF','Hà Nội','https://vnuf.edu.vn','https://lib.vnuf.edu.vn','https://vnuf.edu.vn/tuyensinh',''],
    ['Đại học Sao Đỏ','SDU','Hải Dương','https://saodo.edu.vn','https://lib.saodo.edu.vn','https://saodo.edu.vn/tuyensinh',''],
    ['Đại học Hải Dương','UHD','Hải Dương','https://uhd.edu.vn','','https://uhd.edu.vn',''],
    ['Đại học Kinh tế – Kỹ thuật Công nghiệp','UNETI','Hà Nội','https://uneti.edu.vn','https://lib.uneti.edu.vn','https://uneti.edu.vn/tuyensinh',''],
    ['Đại học Công nghiệp Việt Trì','VIU','Phú Thọ','https://vui.edu.vn','https://lib.vui.edu.vn','https://vui.edu.vn/tuyensinh',''],
    ['Đại học Sư phạm Kỹ thuật Vinh','UTE Vinh','Nghệ An','https://utevinh.edu.vn','','https://utevinh.edu.vn',''],
    ['Đại học Hà Nội Mở (trang học liệu)','HOU-HL','Hà Nội','https://hou.edu.vn','','',''],
    ['Đại học Văn hóa Hà Nội','HUC','Hà Nội','https://huc.edu.vn','https://lib.huc.edu.vn','https://huc.edu.vn/tuyensinh',''],
    ['Đại học Thể dục Thể thao Bắc Ninh','UPES','Bắc Ninh','https://upes.edu.vn','','https://upes.edu.vn',''],
    ['Đại học Mỹ thuật Việt Nam','VNUA-Art','Hà Nội','https://mythuatvietnam.edu.vn','','',''],
    ['Nhạc viện Hà Nội','VNAM','Hà Nội','https://vnam.edu.vn','','https://vnam.edu.vn',''],
    ['Đại học Sân khấu Điện ảnh Hà Nội','HUAFTA','Hà Nội','https://skda.edu.vn','','https://skda.edu.vn',''],
    ['Đại học Nội vụ Hà Nội','HUHA','Hà Nội','https://huha.edu.vn','','https://huha.edu.vn',''],
    ['Đại học Kiểm sát Hà Nội','HPUA','Hà Nội','https://tks.edu.vn','','https://tks.edu.vn',''],
    ['Đại học PCCC','UoFF','Hà Nội','https://daihocpccc.edu.vn','','',''],
    ['Đại học Cảnh sát Nhân dân','PPA','Hà Nội','https://hvcsnd.edu.vn','','https://hvcsnd.edu.vn',''],
    ['Học viện An ninh Nhân dân','PSA','Hà Nội','https://hvannd.edu.vn','','',''],
    ['Đại học Dược Hà Nội','HUP','Hà Nội','https://hup.edu.vn','https://lib.hup.edu.vn','https://hup.edu.vn/tuyensinh',''],
    ['Đại học Y tế Công cộng','HUPH','Hà Nội','https://huph.edu.vn','https://lib.huph.edu.vn','https://huph.edu.vn/tuyensinh',''],
    ['Đại học Kinh tế TP.HCM — CSB','UEH-ISB','TP.HCM','https://isb.edu.vn','','https://isb.edu.vn',''],
    ['Đại học Ngân hàng TP.HCM','HUB','TP.HCM','https://hub.edu.vn','https://lib.hub.edu.vn','https://hub.edu.vn/tuyen-sinh',''],
    ['Đại học Tài chính – Marketing','UFM','TP.HCM','https://ufm.edu.vn','https://lib.ufm.edu.vn','https://ufm.edu.vn/tuyen-sinh',''],
    ['Đại học Giao thông vận tải TP.HCM','UTH2','TP.HCM','https://ut.edu.vn','','',''],
    ['Đại học Y khoa Phạm Ngọc Thạch','PNT','TP.HCM','https://pnt.edu.vn','https://lib.pnt.edu.vn','https://pnt.edu.vn/tuyen-sinh',''],
    ['Đại học Công nghệ Đồng Nai','DNTU','Đồng Nai','https://dntu.edu.vn','https://lib.dntu.edu.vn','https://dntu.edu.vn/tuyen-sinh',''],
    ['Đại học Bình Dương','BDU','Bình Dương','https://bdu.edu.vn','https://lib.bdu.edu.vn','https://bdu.edu.vn/tuyen-sinh',''],
    ['Đại học Quốc tế Hồng Bàng','HIU2','TP.HCM','https://hiu.vn','','',''],
    ['Đại học Gia Định','GDU','TP.HCM','https://giadinh.edu.vn','','https://giadinh.edu.vn',''],
    ['Đại học Công nghệ Sài Gòn','STU','TP.HCM','https://stu.edu.vn','https://lib.stu.edu.vn','https://stu.edu.vn/tuyen-sinh',''],
    ['Đại học Văn Hiến','VHU','TP.HCM','https://vhu.edu.vn','https://lib.vhu.edu.vn','https://vhu.edu.vn/tuyen-sinh',''],
    ['Đại học Ngoại ngữ – Tin học TP.HCM','HUFLIT','TP.HCM','https://huflit.edu.vn','https://lib.huflit.edu.vn','https://huflit.edu.vn/tuyen-sinh',''],
    ['Đại học Quốc tế Sài Gòn','SIU','TP.HCM','https://siu.edu.vn','https://lib.siu.edu.vn','https://siu.edu.vn/tuyen-sinh',''],
    ['Đại học Kinh tế – Tài chính TP.HCM','UEF','TP.HCM','https://uef.edu.vn','https://lib.uef.edu.vn','https://uef.edu.vn/tuyen-sinh',''],
    ['Đại học FPT TP.HCM','FPT-HCM','TP.HCM','https://hcmuni.fpt.edu.vn','','https://hcmuni.fpt.edu.vn',''],
    ['Đại học FPT Đà Nẵng','FPT-DN','Đà Nẵng','https://daihoc.fpt.edu.vn','','',''],
    ['Đại học Duy Tân','DTU','Đà Nẵng','https://duytan.edu.vn','https://lib.duytan.edu.vn','https://duytan.edu.vn/tuyen-sinh',''],
    ['Đại học Đông Á','DAU','Đà Nẵng','https://donga.edu.vn','https://lib.donga.edu.vn','https://donga.edu.vn/tuyen-sinh',''],
    ['Đại học Kiến trúc Đà Nẵng','DAU-Arch','Đà Nẵng','https://dau.edu.vn','https://lib.dau.edu.vn','https://dau.edu.vn/tuyensinh',''],
    ['Đại học Phan Châu Trinh','PCTU','Quảng Nam','https://pctu.edu.vn','','https://pctu.edu.vn',''],
    ['Đại học Quang Trung','QTU','Bình Định','https://qtu.edu.vn','','https://qtu.edu.vn',''],
    ['Đại học Thái Bình Dương','TBD','Khánh Hòa','https://tbd.edu.vn','','https://tbd.edu.vn',''],
    ['Đại học Yersin Đà Lạt','Yersin','Lâm Đồng','https://yersin.edu.vn','https://lib.yersin.edu.vn','https://yersin.edu.vn/tuyen-sinh',''],
    ['Đại học Tây Đô','TDU','Cần Thơ','https://tdu.edu.vn','https://lib.tdu.edu.vn','https://tdu.edu.vn/tuyen-sinh',''],
    ['Đại học Nam Cần Thơ','DNC','Cần Thơ','https://nctu.edu.vn','https://lib.nctu.edu.vn','https://nctu.edu.vn/tuyen-sinh',''],
    ['Đại học Võ Trường Toản','VTTU','Hậu Giang','https://vttu.edu.vn','','https://vttu.edu.vn',''],
    ['Đại học Cửu Long Vĩnh Long','MKU2','Vĩnh Long','https://mku.edu.vn','','',''],
    ['Đại học Kinh tế Nghệ An','NAUE','Nghệ An','https://naue.edu.vn','','https://naue.edu.vn',''],
    ['Đại học Hà Nội Thương mại','TMU2','Hà Nội','https://tmu.edu.vn','','',''],
    ['Viện Toán ứng dụng và Tin học HUST','SAMI','Hà Nội','https://sami.hust.edu.vn','https://sami.hust.edu.vn/sohoa','','https://sami.hust.edu.vn'],
    ['Khoa Toán–Tin HUST (FaMI)','FaMI','Hà Nội','https://fami.hust.edu.vn','','','']
  ];

  unis.forEach(function (u) {
    var name = u[0], short = u[1], region = u[2], home = u[3], lib = u[4], ts = u[5], lms = u[6];
    if (home) {
      pack.push(it('vn', '🏫', name, short,
        'Cổng ' + name + ' (' + region + '): chương trình đào tạo, tài liệu học tập, hướng dẫn sinh viên và thông tin khoa Toán/kỹ thuật.',
        home, ['Đại học', region, 'Hướng dẫn']));
    }
    if (lib) {
      pack.push(it('vn', '📚', 'Thư viện — ' + short, name,
        'Thư viện ' + name + ': giáo trình, sách, học liệu số, luận văn, hướng dẫn học tập và tra cứu tài liệu Toán.',
        lib, ['Thư viện', 'Giáo trình', region]));
    }
    if (ts) {
      pack.push(it('exam', '📝', 'Tuyển sinh & đề thi — ' + short, name,
        'Cổng tuyển sinh ' + name + ': đề án, đề thi / ĐGNL / đánh giá tư duy, hướng dẫn ôn Toán và thông tin xét tuyển.',
        ts, ['Đề thi', 'Tuyển sinh', region]));
    }
    if (lms) {
      pack.push(it('vn', '💻', 'Học liệu / LMS — ' + short, name,
        'Hệ thống bài giảng, tài liệu môn học, bài tập và hướng dẫn học tập trực tuyến của ' + name + '.',
        lms, ['LMS', 'Bài giảng', region]));
    }
  });

  var exams = [
    ['Kỳ thi Đánh giá tư duy — HUST','HUST','https://tsa.hust.edu.vn','Đề thi, cấu trúc bài thi TSA, đề mẫu và hướng dẫn ôn Toán–Đọc hiểu–Khoa học của Bách khoa Hà Nội.','TSA','Đề mẫu'],
    ['Kỳ thi ĐGNL ĐHQG TP.HCM','ĐHQG-HCM','https://thinangluc.vnuhcm.edu.vn','Đề thi đánh giá năng lực ĐHQG-HCM, hướng dẫn ôn, lịch thi và tài liệu ôn Toán–logic.','ĐGNL','Đề thi'],
    ['Cổng ĐGNL ĐHQG-HCM (tuyển sinh)','ĐHQG-HCM','https://tuyensinh.vnuhcm.edu.vn','Đề án, tổ hợp, hướng dẫn thí sinh và thông tin kỳ ĐGNL phía Nam.','ĐGNL','Hướng dẫn'],
    ['HSA — Đánh giá năng lực ĐHQGHN','ĐHQGHN','https://hsa.edu.vn','Kỳ thi HSA của ĐHQG Hà Nội: cấu trúc đề, tài liệu ôn và hướng dẫn đăng ký.','HSA','Đề thi'],
    ['Tra cứu điểm thi tốt nghiệp THPT','Bộ GDĐT','https://diemthi.thitotnghiepthpt.edu.vn','Cổng chính thức tra cứu điểm thi tốt nghiệp THPT toàn quốc.','Điểm thi','Chính thức'],
    ['Cổng thông tin thi tốt nghiệp THPT','Bộ GDĐT','https://thitotnghiepthpt.edu.vn','Thông tin kỳ thi tốt nghiệp: lịch thi, quy chế, hướng dẫn thí sinh.','Kỳ thi','Hướng dẫn'],
    ['Đề thi minh họa tốt nghiệp — Bộ GDĐT','Bộ GDĐT','https://moet.gov.vn','Công bố đề minh họa, đề thi chính thức và đáp án Toán tốt nghiệp THPT trên cổng Bộ.','Đề minh họa','Đáp án'],
    ['Tuyển sinh HUST','HUST','https://ts.hust.edu.vn','Đề án tuyển sinh, TSA, hướng dẫn ôn và thông tin xét tuyển Bách khoa Hà Nội.','Tuyển sinh','TSA'],
    ['Tuyển sinh HCMUT','HCMUT','https://ts.hcmut.edu.vn','Đề án, phương thức xét tuyển và hướng dẫn thí sinh vào Bách khoa TP.HCM.','Tuyển sinh','Đề án'],
    ['Chuyên KHTN — đề HSG','HUS','https://hsgs.edu.vn','Trường THPT chuyên Khoa học Tự nhiên: đề thi HSG, chuyên đề Toán, hướng dẫn ôn đội tuyển.','HSG','Đề thi'],
    ['Chuyên Amsterdam','HN-AMS','https://www.hn-ams.edu.vn','THPT chuyên Hà Nội – Amsterdam: tài liệu, đề thi và hoạt động học thuật Toán.','Chuyên','Đề thi'],
    ['Chuyên Sư phạm Hà Nội','HNUE','https://thptchuyen.hnue.edu.vn','THPT chuyên ĐHSP Hà Nội: đề thi, chuyên đề Toán và hướng dẫn ôn HSG.','Chuyên','HSG'],
    ['Chuyên Lê Hồng Phong TP.HCM','LHP-HCM','https://www.thpt-lehongphong-tphcm.edu.vn','Trường chuyên Lê Hồng Phong: đề thi, chuyên đề và tài liệu ôn Toán HSG phía Nam.','Chuyên','Đề thi'],
    ['Chuyên Trần Đại Nghĩa','TĐN','https://trandainghia.edu.vn','THPT chuyên Trần Đại Nghĩa: chương trình song ngữ, đề thi và hướng dẫn học tập.','Chuyên','Hướng dẫn'],
    ['Chuyên Lê Quý Đôn Đà Nẵng','LQĐ-ĐN','https://thptlequydon.danang.edu.vn','Trường chuyên Lê Quý Đôn Đà Nẵng: đề thi HSG, chuyên đề Toán miền Trung.','Chuyên','HSG'],
    ['Quốc Học Huế','Quốc Học','https://thpt-quochoc-hue.edu.vn','THPT chuyên Quốc Học Huế: đề thi, truyền thống HSG Toán và tài liệu ôn tập.','Chuyên','Đề thi'],
    ['Chuyên Lam Sơn Thanh Hóa','Lam Sơn','https://thptchuyenlamson.edu.vn','THPT chuyên Lam Sơn: đề thi HSG, chuyên đề Toán Thanh Hóa.','Chuyên','HSG'],
    ['Chuyên Phan Bội Châu Nghệ An','PBC','https://thptchuyenpbc.edu.vn','THPT chuyên Phan Bội Châu: đề thi, hướng dẫn ôn HSG Toán Nghệ An.','Chuyên','Đề thi'],
    ['Chuyên Lê Hồng Phong Nam Định','LHP-NĐ','https://www.thptchuyenlhp.edu.vn','Trường chuyên Lê Hồng Phong Nam Định: đề thi HSG và chuyên đề Toán.','Chuyên','HSG'],
    ['Chuyên Nguyễn Huệ Hà Nội','Nguyễn Huệ','https://c3nguyenhue.edu.vn','THPT chuyên Nguyễn Huệ: đề thi, tài liệu ôn Toán khu vực Hà Đông.','Chuyên','Đề thi'],
    ['Chuyên Bắc Ninh','CBN','https://thptchuyenbacninh.edu.vn','THPT chuyên Bắc Ninh: đề thi HSG tỉnh và hướng dẫn ôn tập.','Chuyên','HSG'],
    ['Chuyên Hưng Yên','CHY','https://thptchuyenhungyen.edu.vn','THPT chuyên Hưng Yên: đề thi, chuyên đề Toán.','Chuyên','Đề thi'],
    ['Chuyên Biên Hòa Hà Nam','Hà Nam','https://thptchuyenbienhoa.edu.vn','THPT chuyên Biên Hòa (Hà Nam): đề thi HSG và tài liệu ôn.','Chuyên','HSG'],
    ['Chuyên Thái Nguyên','CTN','https://thptchuyentn.edu.vn','THPT chuyên Thái Nguyên: đề thi, hướng dẫn ôn Toán.','Chuyên','Đề thi'],
    ['Chuyên Hạ Long','Hạ Long','https://thptchuyenhalong.edu.vn','THPT chuyên Hạ Long (Quảng Ninh): đề thi HSG và chuyên đề.','Chuyên','HSG'],
    ['Chuyên Trần Phú Hải Phòng','Trần Phú','https://thptchuyentranphu.edu.vn','THPT chuyên Trần Phú Hải Phòng: đề thi, tài liệu ôn Toán.','Chuyên','Đề thi'],
    ['Chuyên Vĩnh Phúc','CVP','https://thptchuyenvinhphuc.edu.vn','THPT chuyên Vĩnh Phúc: đề thi HSG tỉnh.','Chuyên','HSG'],
    ['Chuyên Hùng Vương Phú Thọ','HV-PT','https://thptchuyenhungvuong.edu.vn','THPT chuyên Hùng Vương: đề thi và chuyên đề Toán Phú Thọ.','Chuyên','Đề thi'],
    ['Chuyên Bắc Giang','CBG','https://thptchuyenbacgiang.edu.vn','THPT chuyên Bắc Giang: đề thi HSG, hướng dẫn ôn.','Chuyên','HSG'],
    ['Chuyên Nguyễn Trãi Hải Dương','NT-HĐ','https://thptchuyennguyentrai.edu.vn','THPT chuyên Nguyễn Trãi: đề thi Toán Hải Dương.','Chuyên','Đề thi'],
    ['Chuyên Lương Văn Tụy Ninh Bình','LVT','https://thptchuyenluongvantuy.edu.vn','THPT chuyên Lương Văn Tụy: đề thi HSG Ninh Bình.','Chuyên','HSG'],
    ['Chuyên Lê Khiết Quảng Ngãi','Lê Khiết','https://thptchuyenlekiet.edu.vn','THPT chuyên Lê Khiết: đề thi, chuyên đề Toán Quảng Ngãi.','Chuyên','Đề thi'],
    ['Chuyên Lê Quý Đôn Bình Định','LQĐ-BĐ','https://thptlequydon.binhdinh.edu.vn','THPT chuyên Lê Quý Đôn Quy Nhơn: đề thi HSG.','Chuyên','HSG'],
    ['Chuyên Lương Thế Vinh Đồng Nai','LTV','https://thptchuyenluongthevinh.edu.vn','THPT chuyên Lương Thế Vinh: đề thi HSG Đồng Nai.','Chuyên','Đề thi'],
    ['Chuyên Thoại Ngọc Hầu An Giang','TNH','https://thptthoai.angiang.edu.vn','THPT chuyên Thoại Ngọc Hầu: đề thi, tài liệu ôn ĐBSCL.','Chuyên','HSG'],
    ['Chuyên Nguyễn Đình Chiểu Bến Tre','NĐC','https://thptchuyennguyendinhchieu.edu.vn','THPT chuyên Nguyễn Đình Chiểu: đề thi HSG Bến Tre.','Chuyên','Đề thi'],
    ['Chuyên Tiền Giang','CTG','https://thptchuyentiengiang.edu.vn','THPT chuyên Tiền Giang: đề thi và hướng dẫn ôn Toán.','Chuyên','HSG'],
    ['Chuyên Lý Tự Trọng Cần Thơ','LTT','https://thptchuyenlytutrong.edu.vn','THPT chuyên Lý Tự Trọng: đề thi HSG Cần Thơ.','Chuyên','Đề thi'],
    ['THPT Thực hành Sư phạm Cần Thơ','CTU-TH','https://thptthuchanh.ctu.edu.vn','Trường thực hành ĐH Cần Thơ: tài liệu, đề thi và hướng dẫn học tập.','Thực hành','Đề thi'],
    ['Khoa Toán–Tin HNUE','HNUE Toán','https://math.hnue.edu.vn','Khoa Toán–Tin ĐHSP Hà Nội: giáo trình sư phạm Toán, đề thi, hướng dẫn ôn HSG.','Giáo trình','HSG'],
    ['Khoa Toán–Tin HCMUS','HCMUS Toán','https://www.math.hcmus.edu.vn','Khoa Toán–Tin HCMUS: giáo trình, đề thi Olympic sinh viên, seminar.','Giáo trình','Olympic SV']
  ];
  exams.forEach(function (e) {
    pack.push(it('exam', '📄', e[0], e[1], e[3], e[2], [e[4], e[5]]));
  });

  var sogd = [
    ['Hà Nội','https://hanoi.edu.vn'],['TP.HCM','https://hcm.edu.vn'],['Hải Phòng','https://haiphong.edu.vn'],
    ['Đà Nẵng','https://danang.edu.vn'],['Cần Thơ','https://cantho.edu.vn'],['Thừa Thiên Huế','https://thuathienhue.edu.vn'],
    ['Nghệ An','https://nghean.edu.vn'],['Thanh Hóa','https://thanhhoa.edu.vn'],['Đồng Nai','https://dongnai.edu.vn'],
    ['Bình Dương','https://binhduong.edu.vn'],['An Giang','https://angiang.edu.vn'],['Đắk Lắk','https://daklak.edu.vn'],
    ['Lâm Đồng','https://lamdong.edu.vn'],['Khánh Hòa','https://khanhhoa.edu.vn'],['Quảng Ninh','https://quangninh.edu.vn'],
    ['Bắc Ninh','https://bacninh.edu.vn'],['Hải Dương','https://haiduong.edu.vn'],['Nam Định','https://namdinh.edu.vn'],
    ['Thái Bình','https://thaibinh.edu.vn'],['Ninh Bình','https://ninhbinh.edu.vn'],['Vĩnh Phúc','https://vinhphuc.edu.vn'],
    ['Phú Thọ','https://phutho.edu.vn'],['Bắc Giang','https://bacgiang.edu.vn'],['Thái Nguyên','https://thainguyen.edu.vn'],
    ['Quảng Nam','https://quangnam.edu.vn'],['Quảng Ngãi','https://quangngai.edu.vn'],['Bình Định','https://binhdinh.edu.vn'],
    ['Phú Yên','https://phuyen.edu.vn'],['Bình Thuận','https://binhthuan.edu.vn'],['Tây Ninh','https://tayninh.edu.vn'],
    ['Long An','https://longan.edu.vn'],['Tiền Giang','https://tiengiang.edu.vn'],['Bến Tre','https://bentre.edu.vn'],
    ['Vĩnh Long','https://vinhlong.edu.vn'],['Đồng Tháp','https://dongthap.edu.vn'],['Kiên Giang','https://kiengiang.edu.vn'],
    ['Sóc Trăng','https://soctrang.edu.vn'],['Bạc Liêu','https://baclieu.edu.vn'],['Cà Mau','https://camau.edu.vn'],
    ['Hậu Giang','https://haugiang.edu.vn'],['Trà Vinh','https://travinh.edu.vn'],['Bà Rịa–Vũng Tàu','https://brvt.edu.vn'],
    ['Bình Phước','https://binhphuoc.edu.vn'],['Đắk Nông','https://daknong.edu.vn'],['Gia Lai','https://gialai.edu.vn'],
    ['Kon Tum','https://kontum.edu.vn'],['Ninh Thuận','https://ninhthuan.edu.vn'],['Quảng Bình','https://quangbinh.edu.vn'],
    ['Quảng Trị','https://quangtri.edu.vn'],['Hà Tĩnh','https://hatinh.edu.vn'],['Hà Nam','https://hanam.edu.vn'],
    ['Hưng Yên','https://hungyen.edu.vn'],['Hòa Bình','https://hoabinh.edu.vn'],['Sơn La','https://sonla.edu.vn'],
    ['Điện Biên','https://dienbien.edu.vn'],['Lai Châu','https://laichau.edu.vn'],['Lào Cai','https://laocai.edu.vn'],
    ['Yên Bái','https://yenbai.edu.vn'],['Tuyên Quang','https://tuyenquang.edu.vn'],['Hà Giang','https://hagiang.edu.vn'],
    ['Cao Bằng','https://caobang.edu.vn'],['Bắc Kạn','https://backan.edu.vn'],['Lạng Sơn','https://langson.edu.vn']
  ];
  sogd.forEach(function (s) {
    pack.push(it('exam', '🏫', 'Sở GDĐT ' + s[0], 'Sở GDĐT ' + s[0],
      'Cổng Sở Giáo dục và Đào tạo ' + s[0] + ': đề thi, đáp án, hướng dẫn ôn tập, công văn chuyên môn và tài liệu bồi dưỡng giáo viên Toán.',
      s[1], ['Sở GDĐT', 'Đề thi', s[0]]));
  });

  var extraOpen = [
    ['exam','📑','Ngân hàng đề thi Olympic sinh viên','Hội Toán học VN','https://www.vms.org.vn','Đề Olympic Toán sinh viên, thông tin hội thi và hướng dẫn đội tuyển.','Olympic SV','Đề thi'],
    ['exam','📰','Báo Dân trí — Giáo dục (đề thi)','Dân trí','https://dantri.com.vn/giao-duc.htm','Tổng hợp đề thi, đáp án tốt nghiệp THPT và hướng dẫn ôn do báo đăng tải theo nguồn Bộ.','Đề thi','Đáp án'],
    ['exam','📰','VnExpress Giáo dục — đề thi','VnExpress','https://vnexpress.net/giao-duc','Đề thi, đáp án, phân tích đề Toán tốt nghiệp và tuyển sinh đại học.','Đề thi','Phân tích'],
    ['exam','📰','Tuổi Trẻ — Giáo dục','Tuổi Trẻ','https://tuoitre.vn/giao-duc.htm','Đề thi, đáp án, hướng dẫn giải Toán kỳ thi tốt nghiệp và ĐGNL.','Đề thi','Hướng dẫn'],
    ['exam','📰','Thanh Niên — Tuyển sinh','Thanh Niên','https://thanhnien.vn/giao-duc.htm','Đề thi, điểm chuẩn, hướng dẫn xét tuyển đại học.','Tuyển sinh','Đề thi'],
    ['vn','📖','Thư viện số dùng chung NALA','NALA','https://digitalknowledgehub.nala.edu.vn','Trung tâm kết nối tri thức số: học liệu mở, giáo trình dùng chung các thư viện đại học.','Học liệu mở','Giáo trình'],
    ['vn','📖','Cổng thông tin thư viện Việt Nam','VLIB','https://vlib.vn','Liên hợp thư viện Việt Nam: tra cứu sách, luận văn liên thông nhiều trường ĐH.','Thư viện','Tra cứu'],
    ['vn','📘','Học viện Khoa học và Công nghệ','GUST','https://gust.edu.vn','Đào tạo sau ĐH của VAST: chuyên đề Toán–Tin, seminar, tài liệu nghiên cứu.','Sau ĐH','Toán'],
    ['vn','📗','Tạp chí Khoa học ĐHQGHN','ĐHQGHN','https://js.vnu.edu.vn','Công bố khoa học, bài báo Toán–Giáo dục của ĐHQG Hà Nội.','Tạp chí','Nghiên cứu'],
    ['vn','📗','Tạp chí Phát triển KH&CN ĐHQG-HCM','ĐHQG-HCM','https://stdj.scienceandtechnology.com.vn','Tạp chí khoa học ĐHQG-HCM: bài Toán ứng dụng, giáo dục.','Tạp chí','KHCN'],
    ['lookup','🔍','Cổng Dữ liệu quốc gia','Bộ TT&TT','https://data.gov.vn','Dữ liệu mở quốc gia — thống kê giáo dục, có thể dùng cho chuyên đề xác suất thống kê.','Dữ liệu','Thống kê'],
    ['sgk','📚','Cổng sách giáo khoa điện tử','NXBGD','https://www.hoclieu.vn','Học liệu số SGK Toán các cấp, bài tập và hướng dẫn học tập theo chương trình mới.','SGK','Hướng dẫn']
  ];
  extraOpen.forEach(function (e) {
    pack.push(it(e[0], e[1], e[2], e[3], e[5], e[4], [e[6], e[7]]));
  });

  global.VN_LIB_PACK = pack;
})(typeof window !== 'undefined' ? window : this);
